### ISSUE TITLE
Review k8 configurations and note suggestions for improvement

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#77]

**Comment by shashanksinha89** [comment]
**Docker Image Optimization**

- Publishing golden docker image to [glasswallsolutions](https://hub.docker.com/u/glasswallsolutions) docker registry.

- Reduce layers to decrease the docker image size.

- Using `multi-stage` docker builds.

**k8s improvements**

-  Hosting  glasswallsolutions official `helm-chart` open source repository. This will host all customized  k8s deployments which can simply installed via `helm` package to any k8s cluster.

- Creating single helm chart instead of using independent yaml files for deployment.
